// INITIAL STATE
const pieceValues = {
    rookDk1: 'a8',
    rookDk2: 'h8',
    knightDk1: 'b8',
    knightDk2: 'g8',
    bishopDk1: 'c8',
    bishopDk2: 'f8',
    kingDk: 'd8',
    queenDk: 'e8',
    pawnDk1: 'a7',
    pawnDk2: 'b7',
    pawnDk3: 'c7',
    pawnDk4: 'd7',
    pawnDk5: 'e7',
    pawnDk6: 'f7',
    pawnDk7: 'g7',
    pawnDk8: 'h7',
    rookLt1: 'a1',
    rookLt2: 'h1',
    knightLt1: 'b1',
    knightLt2: 'g1',
    bishopLt1: 'c1',
    bishopLt2: 'f1',
    kingLt: 'd1',
    queenLt: 'e1',
    pawnLt1: 'a2',
    pawnLt2: 'b2',
    pawnLt3: 'c2',
    pawnLt4: 'd2',
    pawnLt5: 'e2',
    pawnLt6: 'f2',
    pawnLt7: 'g2',
    pawnLt8: 'h2'
}

export default pieceValues;